# 🔢 One Hot Encoding (OHE) in NLP

We will understand One Hot Encoding using 3 documents:

- D1: The Food is Good  
- D2: The Food is Bad  
- D3: Pizza is Amazing  

In [1]:
documents = [
    "The Food is Good",
    "The Food is Bad",
    "Pizza is Amazing"
]

## 🔡 Step 1: Preprocessing

- Convert to lowercase
- Tokenize words

In [3]:
from nltk.tokenize import word_tokenize

processed_docs = [word_tokenize(doc.lower()) for doc in documents]
processed_docs

[['the', 'food', 'is', 'good'],
 ['the', 'food', 'is', 'bad'],
 ['pizza', 'is', 'amazing']]

## 📚 Step 2: Vocabulary

Vocabulary = Unique words from all documents

In [7]:
vocab = set()

for doc in processed_docs:
    vocab.update(doc)

vocab = sorted(list(vocab))
vocab

['amazing', 'bad', 'food', 'good', 'is', 'pizza', 'the']

## 🔢 Step 3: One Hot Encoding

Each word is represented as a binary vector:
- One position = 1  
- Rest = 0  

In [14]:
import numpy as np

word_to_index = {word:idx for idx, word in enumerate(vocab)}
word_to_index

{'amazing': 0, 'bad': 1, 'food': 2, 'good': 3, 'is': 4, 'pizza': 5, 'the': 6}

In [23]:
def one_hot(word, vocab_size):
    vector = np.zeros(vocab_size, dtype=int)
    # print(vector)
    if word in word_to_index:
        vector[word_to_index[word]] = 1
    return vector

## 🧪 Step 4: Apply Encoding

In [25]:
encoded_docs = []

for doc in processed_docs:
    encoded_doc = [one_hot(word, len(vocab)) for word in doc]
    # print(f"vector: {encoded_doc}\n")
    encoded_docs.append(encoded_doc)

encoded_docs

[[array([0, 0, 0, 0, 0, 0, 1]),
  array([0, 0, 1, 0, 0, 0, 0]),
  array([0, 0, 0, 0, 1, 0, 0]),
  array([0, 0, 0, 1, 0, 0, 0])],
 [array([0, 0, 0, 0, 0, 0, 1]),
  array([0, 0, 1, 0, 0, 0, 0]),
  array([0, 0, 0, 0, 1, 0, 0]),
  array([0, 1, 0, 0, 0, 0, 0])],
 [array([0, 0, 0, 0, 0, 1, 0]),
  array([0, 0, 0, 0, 1, 0, 0]),
  array([1, 0, 0, 0, 0, 0, 0])]]

## 🔍 Understanding

Each word becomes a vector.

Example:
- food → [1,0,0,...]
- pizza → [0,1,0,...]

Each word lies on a separate axis (no relationship between them).

## ✅ Advantages

1. Easy to implement using Python  
   (sklearn OneHotEncoder, pandas get_dummies)

2. Simple and fast  
   (no training required)

## ❌ Disadvantages (Very Important)
### 1️⃣ Sparse Matrix → Overfitting

👉 Most values are 0

Example:

[0,0,0,0,1,0,0]

💡 With large vocab (50k words) → huge sparse matrix

### 2️⃣ Fixed Input Size

👉 Vocabulary must be predefined
👉 New word → problem

### 3️⃣ No Semantic Meaning ❌
good ≠ amazing (but meaning is similar)

Vectors:

good    → [0,0,0,1,0,0,0]
amazing → [0,0,0,0,0,0,1]

👉 No similarity captured

### 4️⃣ Out Of Vocabulary (OOV)

👉 New word:

"delicious"

❌ Not in vocab → cannot represent

## 🧠 Memory Trick (From Your Image)

👉 Think:

- Each word = separate axis
- No connection between axes
## ⚡ Final Understanding
- Word → Unique ID (vector)
- Sentence → collection of vectors
## 🎯 Interview One-Liner

👉 One-Hot Encoding represents each word as a binary vector with one active position, but it fails to capture semantic meaning and leads to sparse representations.

## 🧠 Key Takeaway

- One Hot Encoding assigns a unique vector to each word  
- It does not capture meaning or relationships  
- Leads to sparse and high-dimensional data  

## 📦 Example
Sentence:
"I love NLP"
### 🔡 Step 1: Vocabulary
["I", "love", "NLP"]
### 🔢 Step 2: One-Hot Representation
Word	Vector
- I	[1, 0, 0]
- love	[0, 1, 0]
- NLP	[0, 0, 1]

In [2]:
!pip install scikit-learn

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.1/8.1 MB 5.9 MB/s eta 0:00:006.6 MB/s eta 0:00:01m
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.3/20.3 MB 4.4 MB/s eta 0:00:004.4 MB/s eta 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3/3 [scikit-learn]━━━━━ 2/3 [scikit-learn]

[notice] A new release of pip is available: 25.1.1 -> 26.1
[notice] To update, run: pip install --upgrade pip


In [2]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

words = np.array(["I","Love","NLP"]).reshape(-1,1)

encoder = OneHotEncoder(sparse_output=False,dtype=int)
encoded = encoder.fit_transform(words)

print(encoded)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [5]:
sentence = ["I", "love", "NLP", "love"]
print(np.array(sentence).reshape(-1,1))

encoded = encoder.fit_transform(np.array(sentence).reshape(-1,1))

print(encoded)

[['I']
 ['love']
 ['NLP']
 ['love']]
[[1 0 0]
 [0 0 1]
 [0 1 0]
 [0 0 1]]


In [6]:
print(encoder.categories_)


[array(['I', 'NLP', 'love'], dtype='<U4')]


### Top example with OneHotEncoder
documents = [
    "The Food is Good",
    "The Food is Bad",
    "Pizza is Amazing"
]

In [7]:
documents = [
    "The Food is Good",
    "The Food is Bad",
    "Pizza is Amazing"
]

In [9]:
from nltk.tokenize import word_tokenize

words = []

for doc in documents:
    words.extend(word_tokenize(doc.lower()))

words

['the',
 'food',
 'is',
 'good',
 'the',
 'food',
 'is',
 'bad',
 'pizza',
 'is',
 'amazing']

In [11]:
import numpy as np

unique_words = sorted(list(set(words)))

unique_words

['amazing', 'bad', 'food', 'good', 'is', 'pizza', 'the']

In [12]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse_output=False, dtype=int)

words_array = np.array(unique_words).reshape(-1,1)

encoded = encoder.fit_transform(words_array)

encoded

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1]])

In [13]:
for word,vector in zip(unique_words,encoded):
    print(word, "->", vector)

amazing -> [1 0 0 0 0 0 0]
bad -> [0 1 0 0 0 0 0]
food -> [0 0 1 0 0 0 0]
good -> [0 0 0 1 0 0 0]
is -> [0 0 0 0 1 0 0]
pizza -> [0 0 0 0 0 1 0]
the -> [0 0 0 0 0 0 1]


## The Complete example:

In [14]:
documents = [
    "The Food is Good",
    "The Food is Bad",
    "Pizza is Amazing"
]


In [17]:
# Tokenize + Lowecase

processed_docs = [word_tokenize(doc.lower()) for doc in documents]
processed_docs

[['the', 'food', 'is', 'good'],
 ['the', 'food', 'is', 'bad'],
 ['pizza', 'is', 'amazing']]

In [29]:
x= [word for doc in processed_docs for word in doc]
x    

['the',
 'food',
 'is',
 'good',
 'the',
 'food',
 'is',
 'bad',
 'pizza',
 'is',
 'amazing']

In [30]:
# Vocabulary
vocab = sorted(list(set(
    word for doc in processed_docs for word in doc
)))
vocab

['amazing', 'bad', 'food', 'good', 'is', 'pizza', 'the']

In [32]:
# word to index mapping
word_to_index = {word:idx for idx,word in enumerate(vocab)}
word_to_index

{'amazing': 0, 'bad': 1, 'food': 2, 'good': 3, 'is': 4, 'pizza': 5, 'the': 6}

In [38]:
# OneHotEncoding Function
def one_hot(word):
    vector = np.zeros(len(vocab),dtype=int)
    vector[word_to_index[word]] = 1
    return vector

In [41]:
# sentence vectors
for i,doc in enumerate(processed_docs,start=1):
    print(i, "->",doc)
    sentence_vector = np.array([one_hot(word) for word in doc])

    print(f"D{i} Shape:", sentence_vector.shape)
    print(sentence_vector)

1 -> ['the', 'food', 'is', 'good']
D1 Shape: (4, 7)
[[0 0 0 0 0 0 1]
 [0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0]
 [0 0 0 1 0 0 0]]
2 -> ['the', 'food', 'is', 'bad']
D2 Shape: (4, 7)
[[0 0 0 0 0 0 1]
 [0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0]
 [0 1 0 0 0 0 0]]
3 -> ['pizza', 'is', 'amazing']
D3 Shape: (3, 7)
[[0 0 0 0 0 1 0]
 [0 0 0 0 1 0 0]
 [1 0 0 0 0 0 0]]
